# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '././ui/img2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 400, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(220, 440, 591, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.lable_ben = QtWidgets.QLabel(self.centralwidget)
        self.lable_ben.setGeometry(QtCore.QRect(20, 30, 240, 240))
        self.lable_ben.setObjectName("lable_ben")
        self.label_bian = QtWidgets.QLabel(self.centralwidget)
        self.label_bian.setGeometry(QtCore.QRect(810, 30, 240, 240))
        self.label_bian.setObjectName("label_bian")
        self.text_ben = QtWidgets.QLabel(self.centralwidget)
        self.text_ben.setGeometry(QtCore.QRect(70, 300, 54, 12))
        self.text_ben.setObjectName("text_ben")
        self.text_bian = QtWidgets.QLabel(self.centralwidget)
        self.text_bian.setGeometry(QtCore.QRect(910, 300, 54, 12))
        self.text_bian.setObjectName("text_bian")
        self.lable_hu = QtWidgets.QLabel(self.centralwidget)
        self.lable_hu.setGeometry(QtCore.QRect(420, 30, 240, 240))
        self.lable_hu.setObjectName("lable_hu")
        self.text_hu = QtWidgets.QLabel(self.centralwidget)
        self.text_hu.setGeometry(QtCore.QRect(470, 300, 54, 12))
        self.text_hu.setObjectName("text_hu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "起卦"))
        self.lable_ben.setText(_translate("MainWindow", "TextLabel"))
        self.label_bian.setText(_translate("MainWindow", "TextLabel"))
        self.text_ben.setText(_translate("MainWindow", "本卦"))
        self.text_bian.setText(_translate("MainWindow", "变卦"))
        self.lable_hu.setText(_translate("MainWindow", "TextLabel"))
        self.text_hu.setText(_translate("MainWindow", "互卦"))
